services:
  app:
    build: .
    container_name: music-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./static:/root/static
    env_file: .envrc  # This will load all variables from .env

  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: mydb
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: catify
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-cache
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  postgres_data: