version: '3.8'

services:
  app:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - elasticsearch
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
     - POSTGRES_DB=catify
     - POSTGRES_USER=user
     - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    container_name: cache
    restart: always
    command: redis-server --requirepass password  # Set Redis password
    ports:
      - "6379:6379"
  elasticsearch:
    image: elasticsearch:8.17.4
    container_name: elasticsearch
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
    - discovery.type=single-node
    - xpack.security.enabled=falsea
